### ISSUE TITLE
Mobs lagging/slow world loading

### ISSUE THREAD

**Issue by AlbanMarku** [WesCook/Homestead#107]
I've tried to play with modpack multiple times over the past four years. This modpack, no matter how powerful the PC is, always runs poorly. fps is fine but the mobs and chunk loading are very bad. This also includes breaking blocks. Why does this happen? Is it to do with Minecraft 1.10? I play with larger modpacks on the same settings and things run smoothly.

**Comment by WesCook** [comment]
Hi Alban,

AI pathing calculations are often one of the largest negative impacts to TPS.  Sometimes large groups of mobs - especially complex mobs like from Animania - can cause TPS problems.  That is something that is difficult to control for from the perspective of a modpack author because, at least at that time, we had little control over mob spawning rules.

Assuming you're experiencing TPS problems, you can use the built-in [debug function](https://minecraft.fandom.com/wiki/Commands/debug) to generate a profiler chart.  It's not a great UI, but it may point you in the correct direction.

Slow world updates after breaking of blocks are typically caused by excessive event hooks (which I don't believe Homestead has), or complex rendering in the specific chunk which needs to be updated.  You can try setting `B:alwaysSetupTerrainOffThread` to false in the /config/forge.cfg file to see if that has any effect.

1.10 was a transitionary version of Minecraft which meant there wasn't a lot of time to stabilize and work out the kinks.  I did extensive pack testing before release, but that still pales in comparison to the millions of players finding bottlenecks in 1.12 or 1.16.

I also made an effort to feature less common mods in Homestead to make it a more unique experience.  Some of those went on to become mainstay mods in their own right (such as Astral Sorcery), but there's definitely a handful of abandoned or early versions of mods.  You won't find many other packs feature WTF's Expedition for world gen, for example.  That uniqueness provides its own value, but it also means untested, sometimes buggy behaviour with certain configurations.  After release I learned that some of the visual mods conflicted with certain graphics cards, so I disabled those mods by default.

It's been years since I've done development on this modpack, so I won't be releasing any performance enhancements or fixes at this time.  But I hope this sheds some light on why Homestead is different than most other modpacks of its era.

All the same, I hope you're able to find solutions to the problems you experience with the pack.  And if not, I thank you for giving it a fair shake anyway.

**Comment by AlbanMarku** [comment]
Setting it to false didn't fix the tick lag unfortunately. Mobs still freezing and blocks not breaking. It's a shame since this is my favourite modpack in theory but just can't play it.

**Comment by zeeky4** [comment]
uncapping my fps actually worked for me, i'm not sure the mechanism but the difference is night and day
