### ISSUE TITLE
[Suggestion] Add recipe for Immersive Craft's rocks

### ISSUE THREAD

**Issue by EchoingZen** [WesCook/Homestead#11]
Having exhausted my local supply of rocks for rock paths and water strainers, I was wondering if there is a chance you would add a recipe for rocks?

This would help people who start on a small island who use up all the local supply or people like me who have an unhealthy attachment to rock paths.

Cobblestone and IE's hammer?  Something like that.

**Comment by WesCook** [comment]
Hey Zen,

Thanks for the suggestion.

The decision to not have a recipe for rocks was actually very intentional, as I use it as an easy to get, but otherwise non-renewable resource.  This makes it great for things like water strainers as they can't be easily farmed for infinite iron, but are still available early-game.

However I do agree that rock paths should be cheaper.  I've made a note to increase the number of paths you get from each craft in the next version.

I don't have an ETA right now, as the pack is in a stable state as far as I know.  I tend to make notes as I play myself or as people report bugs.  Once enough items fill that list to justify a new update, I'll get it out there.

In the mean time, if you'd like to you can rebalance this yourself by editing `/scripts/housing.zs` and increasing the value on this line from 16 to 64:

`recipes.addShapeless(<furniture:rock_path> * 16, [<immcraft:rock>, <immcraft:rock>]);`

I'm going to close this issue for now as I've already made a note of it in my todo list.  Thank you.

**Comment by EchoingZen** [comment]
Thanks for the reply.  :)

**Comment by WesCook** [comment]
Just as a heads up, this has been patched officially in v1.4.
