### ISSUE TITLE
Beds crash everything

### ISSUE THREAD

**Issue by burlingk** [WesCook/Homestead#13]
Using a bed in single player doesn't work properly.

Once the sun comes up, you don't get up.  When you press "Get out of bed," it gives you the option to get kicked from the server (Which of course doesn't work well in single player).

Only option to continue the game is to actively kill the client and wait for it to reload all the mods again to continue.

**Comment by WesCook** [comment]
Believe it or not this is actually a [vanilla bug](https://bugs.mojang.com/browse/MC-92216), although it's typically made worse in a modded environment.

The mod Bed Bugs is supposed to help alleviate the issue by allowing you to kick yourself back to the main menu if you get stuck, and I believe this works in both singleplayer and multiplayer.

Can you describe what happens when you click the Kick Me button?  Though not ideal, if it kicks you back to the menu that's the best option we have right now.

**Comment by burlingk** [comment]
Ok.  I saw it in another  pack also, earlier today.  Next time it happens I will pay more attention.  I'll also try to remember to play with the logs running when using larger packs.

Basically though, short version, it freezes up until I use task manager to kill the process.

**Comment by WesCook** [comment]
I'll close this for now as I believe this to be a vanilla-specific bug.  If it occurs again, let me know and I'll reassess.

Thanks.
