### ISSUE TITLE
I had to remove betterfps

### ISSUE THREAD

**Issue by nedellis** [WesCook/Homestead#20]
It was causing me huge lag spikes and black screen when i was floating on water surface (right when i was about to emerge or submerge from water).

**Comment by WesCook** [comment]
Hey nedellis, thanks for the report.

It sounds like EnhancedVisuals may actually be at fault, as it applies a shader effect when entering and exiting water.  It also doesn't play well with some graphics cards/drivers.  So that would be my guess, if you'd like to investigate further.

It's also possible there's a conflict between the two mods.  Though I've not actually gotten any performance complaints surrounding this issue before.  If I do in the future, I might elect to remove one of the two mods.

**Comment by WesCook** [comment]
As I believe this is a GPU or driver-specific issue, I'm going to close this issue for now.  If you learn more or if others have the same issue, please feel free to reply further.  At the very least I could mark the relevant mods as less stable under certain configurations.

**Comment by nedellis** [comment]
Ok, i discovered lag spikes was actually done by ram that doesn't go above 2gb, even if 4gb is enabled into ATLauncher.

**Comment by nedellis** [comment]
I updated Java and Better fps black screen has been fixed. Sorry for that, tought java was already autoupdated.
