### ISSUE TITLE
(Balance) Some pam's juices are not worthing

### ISSUE THREAD

**Issue by nedellis** [WesCook/Homestead#21]
For example Apple Juice restores 1.5% Fruit while a single apple restores 2%, or Carrot Juice restores 1.5% while single carrot restores 1.5%.  
Also apple juice from Tough as nails is reduntant with Apple Juice from pam and it gives different effects. 

Any way to balance that?

**Comment by WesCook** [comment]
Thanks for your input.

It's tough to balance foods and drinks because their nutritional value is dynamic, and based upon the hunger value of the food as decided by the mod author.  So I'm not actually specifying the nutritional value of any foods myself.

In the case of apples vs apple juice, the small loss in hunger/nutrition is probably due to the speed boost it grants you.  That's a design decision by Pam though, so I can only speculate.  There's also the Tough as Nails variant, however that's required to grant thirst.

Unfortunately I still have no way to have juices from other mods quench thirst yet, but I'd like to add that in the future if it becomes possible.  That would help reduce the redundancy you pointed out.

The situation is similar for carrot juice.  My guess is Pam reduced the hunger value to balance it, and similarly the TAN juice is there just to provide thirst.

Ultimately I can see how a few items might seem out of whack in their balance, but getting into the business of balancing a mod as expansive as Harvestcraft is quite the undertaking, and from the testing I've done I think it works pretty well as-is.

If nothing else, it gives players an excuse to work out the best foods for themselves.  :)

I'm going to mark this as closed as I don't believe it requires further action.  I'd be glad to hear any follow up comments however.
