### ISSUE TITLE
Houston, we (may) have a problem.

### ISSUE THREAD

**Issue by krzys189** [WesCook/Homestead#25]
I cant seem to craft bolt cores, also the bolt crafting menu is a bit screwed up, when you put the fletching into tho fletching spot it does not count as it being in the right spot, instead you have to go to the arrow crafting and put the fletching there, after you have done this open the bolt crafting menu again without moving the fletching, then the fletching will be in a hidden little square and only then it will count.

**Comment by WesCook** [comment]
It seems that bolt crafting has changed.  Instead of a tool rod, you must now use an arrow shaft.  You can then pour metal on it using the smeltery.  This is discussed towards the front of the Tools section in the Materials and You book.

As for your second issue, I'm afraid I wasn't able to replicate this.  I was able to successfully craft a bolt by using the bolt menu.

**Comment by krzys189** [comment]
Thanks! Im not sure what is wrong with issue 2, but i can live with it.

**Comment by krzys189** [comment]
![screenshot](https://user-images.githubusercontent.com/30729590/28995718-f6097730-79f0-11e7-9b85-cfd86f72f232.png)
This is how it looks for me.

**Comment by WesCook** [comment]
Thanks for the screenshot.  While I did see the Components tab listed two Bolt Cores, I didn't have any problem crafting from a core and a fletching.

Unfortunately this is more of a Tinkers bug than anything I could resolve anyway, so I'm going to mark this as closed for now.  Thanks for letting me know though - I'll keep it in mind if there's any duplicate reports in the future.
