### ISSUE TITLE
Shaderpacks Sky Rendering

### ISSUE THREAD

**Issue by meganleighwoulffe** [WesCook/Homestead#3]
I unfortunately do not know enough about the current mods to figure out what the issue is, but it seems that any shader pack i attempt to use has some sort of issue with sky rendering. Either it's all one shade of color, or there's color flashes, or the sun renders as blue. I can't seem to find a shader pack that works. Everything else works (waving foliage, water reflection, shadows, etc) but the sky rendering is always wrong. Is there any shader pack that you know of that works with Homestead?

**Comment by WesCook** [comment]
No, I'm afraid not.  The sky rendering is - I believe - incompatible with Astral Sorcery.  I had the same issue when I tested shader mods.

There is a setting to have reduced rendering in the Astral sorcery config.  It's called `weakSkyRenders`, and may improve compatibility.  You would need to test that though.

Note that Optifine also has a setting for custom skies, but I believe that pertains to texture packs.  I had a similar issue there, which is why that setting is disabled by default.
