### ISSUE TITLE
Crashing Worlds

### ISSUE THREAD

**Issue by KittehRenja** [WesCook/Homestead#4]
Hi, my fiance and I seem to be having an issue of the game crashing on occasion during gameplay, and several worlds now crash to ATLauncher a few seconds after loading into the world.
The only extra mod we've added is JourneyMap, and we have plenty of RAM allocated on the launcher.
I'm not currently at home so I cannot upload any logs, but any help you can offer would be greatly appreciated!

**Comment by WesCook** [comment]
Hi Kitteh,

Crashing isn't so good.  I'll definitely need to take a look at the crashlogs to figure out what's going on though, as with modded Minecraft there's also a hundred things that could be the cause.

You can find your crashlogs in your instance directory under the `/crash-reports` folder.  Upload them to a server like Pastebin or Github Gists, and I'll see if I can learn anything more from them.

If you could clarify as well, are both of you experiencing the same crash (same error in the log)?  Are you running on the same computer, or different devices?  And finally, does this seem to be world-specific or does it apply to every world?

That should help narrow things down as well.

**Comment by KittehRenja** [comment]
https://gist.github.com/KittehRenja/e8e6730fea7b176a85a57111a99c8813

This is the most recent crash-report, the world loads and opens, then a few seconds later crashes to desktop. It's the second single-player world to do so unfortunately. 

We play LAN on two pc's; and I've tried copying the world to my computer to run it from there but the same crash happens.

**Comment by KittehRenja** [comment]
It looks to me like it might actually be frogs from the mod Animania making us crash, I'll see if disabling frog spawning completely in the config files fixes our problem!

- UPDATE -
Yup. Apparently that's what the problem was. Disabling frog spawning stopped our worlds from crashing. Perhaps we are not the only ones who have experienced this issue, but it seems to be resolved! We can continue using this awesome modpack now! (:

**Comment by WesCook** [comment]
Thanks for the information.  From the crashlog, it looks like SoundPhysics and Animania are having a conflict.  I haven't seen that before now, and due to Animania being closed source it makes it harder to investigate.

I'll create a bug report with the relevant mod authors to see if this can be fixed.  In the mean time however, you should be able to disable SoundPhysics by reinstalling your ATL instance and unchecking that mod in the selection (note: this will also overwrite your Journeymap install).

If you'd still like to keep the nicer audio reverb effects in the mean time, then you can install [Sound Filters](https://minecraft.curseforge.com/projects/sound-filters) instead.  You might also consider slightly lowering the blocks to check to improve performance, as detailed in [this post](https://www.reddit.com/r/feedthebeast/comments/5zr7zq/psa_sound_filters_can_cause_steady_lag_spikes_if/).

---

>It looks to me like it might actually be frogs from the mod Animania making us crash

Indeed it is a Tree Frog in this case.  I'm not sure if it's just this animal, or any Animania mob.  If that solves the problem without needing to make any other changes though, then that would be another solution.

**Comment by WesCook** [comment]
I've done some more testing and have been able to replicate this bug.  It appears to only occur in singleplayer or LAN play, but not on dedicated servers.  It also occurs if only these two mods are installed, making it easier to reproduce.

I'm reporting to the relevant trackers now.

**Comment by WesCook** [comment]
This issue has been fixed in in v1.3 of Homestead.  You can reenable frogs again if you'd like.  :)
