### ISSUE TITLE
Walking sounds not working?

### ISSUE THREAD

**Issue by Naphrym** [WesCook/Homestead#52]
The sounds that should play when the player or a mob walks are not working for me. All other block sounds work and I've reloaded my client.

I am using the Sound Physics mod.

Edit: It seems the sounds occasionally play very briefly.

**Comment by Mac15001900** [comment]
I just came here to report the same issue. Turning sound subtitles on, I can confirm that player footsteps sounds are not playing at all (while other entities' are).

**Comment by WesCook** [comment]
Has this issue only started in Homestead 1.7?  I'll take a look, thanks.

**Comment by Naphrym** [comment]
I played on 1.6 only briefly (found this pack last night), but iirc, this wasn't a problem before the 1.7 update

**Comment by WesCook** [comment]
I'm able to confirm this bug occurs in 1.7, but not 1.6.  I'll see if I can figure out what's changed.

Thanks for the reports!

**Comment by WesCook** [comment]
It looks like this is caused by the `DynamicSurroundings-1.10.2-3.4.7.2.jar` update.  `DynamicSurroundings-1.10.2-3.4.7.1.jar` doesn't present with this issue.

Likely related to https://github.com/OreCruncher/DynamicSurroundings/issues/174.  I'll add some info to that bug report, and roll back the mod in the next pack update.

**Comment by WesCook** [comment]
I've pushed a new update which should resolve this issue.  Thanks again for the report!
