### ISSUE TITLE
No place to ask for help

### ISSUE THREAD

**Issue by crashoverride81** [WesCook/Homestead#57]
Yes i know this is an issue tracker but am trying to get help on something...Seen the silo in the farm2.png image and wanna know how to automated putting in stuff into the silos! cant tell from the image how to do it! Is there a forum for this kind of help?

**Comment by WesCook** [comment]
Hey,

Not a big deal, though the best way to find this sort of info is usually to search for the item from the relevant mod, rather than the modpack.  For instance the Silo is from Immersive Engineering, so a quick search brings up the community wiki page on it:

>Items can be piped into the top block, and removed through the bottom block. Removal of items requires a Redstone signal.

https://ftb.gamepedia.com/Silo

You should be able to pipe items in using hoppers, wooden hoppers, conveyor belts, or any other mechanism that can transfer items into an inventory.

**Comment by crashoverride81** [comment]
whats the haft and pully used for in the image then cause i tried that and it wont pull from the millstone!

**Comment by WesCook** [comment]
These are just decorative, taken for the screenshot. The pulley system is actually an elevator from BetterWithMods. The hopper is a set of microblocks.

I'm not sure what you mean by pulling from the millstone, but generally it's activated automatically and the drops are picked up. It may not allow automatic output.
