### ISSUE TITLE
Animania troughs disappearing

### ISSUE THREAD

**Issue by jchen1210** [WesCook/Homestead#70]
Shortly after animals eat wheat from an Animania trough, the trough disappears, I haven't directly seen this myself, but sometimes the troughs disappear right after i fill them with wheat. Also just as a question, The One Probe shows me that some of my ewes are ready to milk but I am unable to milk them. Is it because of the bucket I am using or something else? I have tried clay and normal iron buckets and when they do work, I get vanilla milk.

**Comment by jchen1210** [comment]
Ok now I realized that they are providing normal milk because they are unhappy, but I can't seem to find out why. The One Probe tells me that they're perfectly fine, well fed, hydrated, and everything but I have 2 ewes that are always unhappy.

**Comment by WesCook** [comment]
Animals will give off black particles from Weakness when they're unhappy, so that will let you know at a glance.  As to what might be causing their unhappiness, I could only speculate.

Regarding animals providing milk though, please note they need to have given birth first.  This change was introduced with Animania 1.3.

**Comment by WesCook** [comment]
This doesn't seem like a pack bug, so I'm going to close this for now.
