### ISSUE TITLE
Troubles downloading

### ISSUE THREAD

**Issue by VoteforFlavor** [WesCook/Homestead#71]
Beyond what is in the title, I cannot insert Optifine into the pack. I additionally receive an error message saying I need to have played minecraft 1.10.2 at least once. I have done this now multiple times and the versions above and below it, AND the optifine version. I am at a loss on what to do, even going as far as to download the entirety from GitHub and finding a way to insert it

If you could help I would be so glad to play this pack.

**Comment by WesCook** [comment]
Hi Vote,

Are you using ATLauncher to play the pack?  Github includes the config files and scripts, but that's it.

ATLauncher should automate the entire process including prompting you to download Optifine (which is used in Homestead).

If you are using ATL, can you walk me through the steps of what you're doing and when it goes wrong?

Thanks.

**Comment by VoteforFlavor** [comment]
I am using ATL to launch it. I seem to be having problems others have. However when I get Optifine and put it in the folder it should sit in It will not download into the folder. The error prompt says that I need to play minecraft 1.10.2 at least once.

**Comment by WesCook** [comment]
Is this error showing up in the ATL log?  Can you take a screenshot?

That sounds like an error message that Forge displays when installing into the vanilla Minecraft launcher.  However ATL doesn't use the vanilla launcher, so I can't imagine why that might be happening.

I haven't received any other reports of this issue at this time.

**Comment by VoteforFlavor** [comment]
This is the problem. However I have done this already. Even getting homestead to run without optifine. Its the weirdest thing because I have launched that version of minecraft normally and on ATL
Link: https://gyazo.com/42e9855baa55583de78ef650e9f67e70

**Comment by VoteforFlavor** [comment]
Additionally here should be the full log
http://paste.atlauncher.com/view/d42a1c6d
Everytime Optifine comes up it says it is disabled

**Comment by WesCook** [comment]
Your log seems to have lots of sound system errors, but it doesn't look like an actual crash is present.  It looks like you were actually able to load a world.

Am I understanding correctly that everything works if you leave Optifine unchecked in the optional mods screen, but it refuses to download or play when Optifine is checked?

In the background of your screenshot it looks like you're running an installer for Optifine.  You want to make sure that you download the linked file and drop it in ATL's downloads folder, rather than install it anywhere.  The installer makes mention of the official Minecraft launcher, so it seems possible that's related to this error.

**Comment by WesCook** [comment]
I'm not sure this is a pack-related bug, so I'm going to close this for now.  If you can provide more information I'll try to add offer any other suggestion, but it does seem like you're able to load the pack from the log above.  The specific issue may be with ATLauncher itself, or as a result of how Optifine is being installed (it should just be dropped in the Downloads folder).
