### ISSUE TITLE
Unable to complete a quest

### ISSUE THREAD

**Issue by DarkriGaming** [WesCook/Homestead#74]
I am unable to complete the quest where you must discover a pig in the "Farm Life" section of the quest book. Whenever i go near an Animalia pig (As in a sow and the other variants added from the mod) It does not accept that as completing the quest, the other problem is that no "Normal" Pigs spawn in the game (and cannot be spawned using an egg either). If anyone has a solution please let me know.

**Comment by WesCook** [comment]
It sounds like you have a very old version of the quest book data.  You'll need to update it manually when you update the pack.

Can you try running these instructions?

>**Note:** Existing worlds will not automatically receive quest changes on pack updates.  On clients, you can run `/bq_admin default load` as an op to update existing worlds.  On servers, please copy the file `/config/betterquesting/DefaultQuests.json` over `/world/betterquesting/QuestDatabase.json`.

**Comment by DarkriGaming** [comment]
Alright that seemed to have worked! Thank you!
Iv'e run into one more problem however, for some reason the cows on my farm won't breed, they are in good conditions and happy but haven't bred for days.

**Comment by WesCook** [comment]
The Animania cows have a number of quirks to them that can make some tasks difficult.  For instance if they have a breeding partner nearby but inaccessible, they won't mate with any others.

I'm not sure what the breeding timer is off the top of my head, but it's possible it's just not expired yet.  These issues can be difficult to debug at a glance due to the complexities of the mod.

As the reported issue here is resolved though, I'm going to mark this one as closed.
