### ISSUE TITLE
Milk for cheese in 1.10

### ISSUE THREAD

**Issue by Corrbin** [WesCook/Homestead#76]
I'm having an issue in which I am only able to get the regular minecraft milk from all animals rather than the specialty milk for cheese when they are happy, (yes, I have made extra sure that they were actually happy, gave it some time, tried different breeds of the animals, ect...) and it is hindering the gameplay a bit. I was wondering if you might know where the conflict in the coding might be so that I could fix it, as I'm unable to locate the correct config menu. The Animania config doesn't contain any information about the different milks, though I am still able to get the item when I go into creative, so it's there somewhere. Any help would be appreciated! Thanks!

**Comment by WesCook** [comment]
I've seen it reported a couple times that animals won't give specialty milks, but I'm not sure if there's an actual bug here or if the animals are just really picky.  Testing in a new world usually shows the animals to be more cooperative.  Note they also need to give birth before offering milk.

As for where in the code that might be, Animania is a closed source mod so isn't open to any contributions unfortunately.

**Comment by Corrbin** [comment]
Okay, glad to know it isn't just me. I was wondering where the option to turn off the Minecraft milk would be, though, not the anmania one. XD I figured you might know since you made a modpack with the original. Do you think that creating a new world would fix it in the original seed, though? I get this feeling that the anmania milk just isn't overriding the original.

**Comment by WesCook** [comment]
There is no option to turn off vanilla milk.  Animania has code which will override it when the conditions are correct.

Creating a new world is a temporary solution, because animals are happy by default.  I would not recommend doing so to address this issue.  It's unrelated to world seed.

If you're desperate, you can always use spawn eggs to place fresh cows, replacing old ones.  Just remember they still need to give birth once before they can be milked.

I'm still unsure if there's a real bug here, or if it's just a matter of the animals being very picky in all the conditions they have before giving specialty milks.
