### ISSUE TITLE
ores don't seem to be spawning in anymore

### ISSUE THREAD

**Issue by Deathrider10136** [WesCook/Homestead#8]
I've been playing this pack without any problem but now i need more ores and i cant find any, in the map I'm in a area where the underground is marble and I've been searching but nothing. this one cave all of a sudden had new blocks in it like the lava in marble stuff but thats the only place I've seen ores like that. can you help?

**Comment by WesCook** [comment]
I've just tested and ore is still generating below ground.  To test this for yourself you can open a creative world, drink a night vision potion, enter spectator mode, and start flying around underground.  You should spot some on a cave or ravine wall before too long.

Ores have been purposefully made more rare in this pack, however they are also in much larger pockets.  If you find a Silver vein, for instance, there may be two stacks worth of silver inside.  There's a quest which explains the depths and frequencies of ores on the first page of the quest book.

I've also buffed ore generation a bit in Homestead v1.3, so if you've generated new terrain since then, it may be slightly easier to find.  Caves and ravines are also more frequent, now.

The lava cave you described is an intended feature, and is a useful way to get lava early-game.  Ores can still generate in lava caves.  Just be mindful of ore fracturing...
