### ISSUE TITLE
Server Odd Issue

### ISSUE THREAD

**Issue by Nick111567** [WesCook/Homestead#92]
Ok, I'm not sure why this is happening but when I use AT Launcher to create a server I noticed that the bone plus ash (From charcoal pit mod) doesn't make 5 bonemeal, its not in the crafting list anymore either? It works in the instance that is the same version. This alone isn't a problem at all to be honest, I am just now worried that if this recipe was lost when I switched to the server is there other recipes that might also have gotten lost? This makes me nervous to continue playing, i would hate to get to a point where a key item is uncraftable or another mod isn't working right or something ya know? Any idea why this is or what I need to do to fix this?

Thanks,
Nick111567

**Comment by WesCook** [comment]
Hi Nick,

Just to be sure, you're using the same pack version on both installs, right?  The CraftTweaker scripts (recipes) being downloaded shouldn't be any different.

Here is the recipe you mentioned specifically:

https://github.com/WesCook/Homestead/blob/master/scripts/farming.zs#L37-L38

I'd double check that all scripts are in there, and that they're not different between your installs.  You can look at this Github repo to see how it's supposed to look.

I've also heard murmurings about some people getting half-completed installs on ATL, but I haven't been able to confirm this myself.  It's a possibility though.

**Comment by Nick111567** [comment]
Ok so all the scripts seem to match, see attached screen shot that shows the instance scrips on the left and the Server scripts on the right. I spot checked a couple of the files, especially the farming one and they looked the exact same except some of the script files on the server aren't spaced the same. Example, transport runs as one really long line instead of being broken up like your example. 
![image](https://user-images.githubusercontent.com/39245553/40026763-56b8d150-579c-11e8-8bfd-5fed35d250c7.png)

I did notice that the modlists don't quite match, theres a size discrepancy, can I just copy over the instance mods? If so what all can I just copy over into the server side to make sure they match?

**Comment by WesCook** [comment]
The issue you mentioned about the lines running together is because notepad.exe doesn't support unix-style linebreaks.  (Microsoft are actually fixing this soon, after many many years).  Java should have no problem understanding them though.

The mods list is actually meant to be different on the server.  Some mods are client-side only and should not be loaded on the server.  I'd recommend against copying them over for that reason.

I'm not too sure what else might be causing the server version to be different for you.  You could try reinstalling the server (backing up your world), or try copying your client world to see if that has any effect (though I don't see why it would...).

Sorry I don't have anything else to suggest.  It doesn't quite make sense though - the content should be equal between both versions.

**Comment by Nick111567** [comment]
I understand. I've already tried installing the server clean, in a new world after just running the server, changing the EULA to TRUE then rerunning and logging in the recipe is still missing. 

Thanks for trying Mr. Wes. If i wanted to setup the server folder without the use of atlauncher, to see if I could find the difference between the two, what would you suggest would be the best way to do that? I believe the homestead files on your page is the client side of the pack.

**Comment by WesCook** [comment]
I've decided to test this out now to see if I can figure out what's going on.  And apparently, this isn't just you.  I'm missing the bone meal recipes on servers too.

It does seem like other CraftTweaker files are being loaded correctly though.  Recipes are adjusted, tooltips are added.  So far the bones + ash recipe is the only one I notice as missing.

Bizarre.

**Comment by Nick111567** [comment]
Figure anything else out? Is it really just that one recipe missing?

**Comment by WesCook** [comment]
That's all I noticed.  The pack has been used on servers since its release and I haven't had any problems reported related to this issue before now.

Other recipes from that file are taking effect, so it doesn't seem to be an issue with line endings or corruption.  I'd report it as a possible bug to the author of CraftTweaker, but we're on an unsupported version now.

Got me.  I wish I knew what was causing that, but it doesn't seem to be causing any major problems elsewhere.  And as there's no fix that I can see, I'm going to have to mark this one as closed yet unfixed.

Thanks for the report though.  You have sharp eyes, and if something comes up again related to this issue I'll know where to look.

**Comment by Nick111567** [comment]
Wes,

I really appreciate your help with this! Like I said from the beginning, if that is the only thing that got lost from translating to a server I'm perfectly fine with that.
Thanks for being awesome,
Nick111567
