### ISSUE TITLE
Tick lag

### ISSUE THREAD

**Issue by mechobree** [WesCook/Homestead#94]
I appear to be having extreme tick lag, it's fine and then most of the time when I mine a block, it reappears again and doesn't drop anything. And the cycle continues. (i do have some extra mods installed but don't believe it's the issue)
Any ideas how to help fix this?
(I'm unsure of what information I need to provide for this issue, if the latest log isn't enough)
[latest log](https://gist.github.com/Artinaix/93e3a77a9796e6658861f6edc770edbe)

**Comment by WesCook** [comment]
Hi Artinaix,

I'm sorry to say, but outside of fixing pack-specific bugs I can't do server profiling for you.  I would suggest looking into [Mojang's profiler tool](https://minecraft.gamepedia.com/Commands/debug) ([explanation here](https://www.reddit.com/r/feedthebeast/comments/5mxn51/vanilla_has_an_built_in_profiler_that_not_a_lot/)), or some mod-specific profiling tools like [LagGoggles](https://minecraft.curseforge.com/projects/laggoggles).  For more advanced uses you may also consider a Java profiler like [WarmRoast](https://github.com/sk89q/WarmRoast).

Performance issues are unfortunately a part of modded Minecraft life, and apply to most packs and servers.  I've done all I could to make Homestead performant, but if you identify something you believe to be specific to the pack then please let me know.  Otherwise unfortunately there's not much else I can suggest.

Cheers.

**Comment by krzys189** [comment]
I get the same tick lag you get, and there aren't really that many solutions.
A)get a better PC(mine is really low end)
B) disable all the mods that make everything look more realistic, like better foliage etc.
C) set your graphics to as low as you are comfortable with
And that pretty much concludes the list.
