### ISSUE TITLE
[Request] Recipe Craftweaker 1.10 

### ISSUE THREAD

**Issue by darknat** [WesCook/Homestead#95]
Hey,

I like your modpack, but I want to upgrade to 1.12 and I have a problem with craftweaker script.

I don't know, I think that the writing has change to the 1.12. I have not found anything or on the wiki, it is to weird.

If you have a time to explain, or give new script, I will be very grateful to you

**Comment by WesCook** [comment]
Hi darknat,

The CraftTweaker scripts are licensed under MIT so you are free to use them if you'd like, but understand that they are written specifically for this set of mods as they existed in Minecraft v1.10.  There isn't any automatic conversion process to make them compatible with 1.12.  The concept doesn't really make sense because many of the mods in Homestead do not even exist on 1.12 yet.

If you enjoy some of the changes I made to the game, I would suggest you port them over in pieces, and modify them to reflect the mods you have installed in your 1.12 pack.  You'll need to replace recipes for many mods that no longer exist, or updates names when IDs have changed.

There isn't anything I can do to make them run correctly in your pack on 1.12.
