### ISSUE TITLE
Clay Bucket does not respect Animania cow's happiness

### ISSUE THREAD

**Issue by bobum** [WesCook/Homestead#97]
I can milk cows all day long in with a clay bucket - just walk up behind them, right click and poof - clay bucket of milk.  But I cannot get it to work with a regular Minecraft bucket made from iron ingots at all.

**Comment by WesCook** [comment]
Hrmm.  Normally a cow should only grant milk when it's happy.  I'm guessing what's happening here is there's an incompatibility between Animania and the Clay Buckets mod.  A regular vanilla bucket should respect Animania's rules, but a clay bucket may always be able to obtain milk.

Could you check if the cow is happy or not?  It'll be unhappy if it has black particles billowing off of it, and a weakness effect in the One Probe GUI.  Thanks!

That's my best guess as to what's causing this inconsistency anyway.

**Comment by bobum** [comment]
Ok tested again per your recommendation and your assumptions are correct - when using the regular bucket - I can only get milk when the circumstances are correct - but the clay buckets, I get it anytime she is ready to be milked.  So the defect is a little different than reported - it's just the inconsistency between the two packs, Animania and the Clay Buckets.  Thanks - close or modify at your will!!

**Comment by WesCook** [comment]
I've updated the title to make it easier to find this bug in the future.  As for a fix, unfortunately we're on a rather outdated version of Minecraft now so mod compatibility bug fixes are pretty unlikely to happen.  It looks like this issue was fixed in Animania only under Minecraft 1.12.

https://github.com/capnkirok/animaniamod/issues/12

So for that reason I'm going to close this as unfixed.

It hasn't come up until now, so I suppose it's not that well known.  If you'd like you can consider this a useful trick when your cows are having a bad day.  :)  Or just stick to metal buckets, if you prefer.

Thanks for the report, and apologies for being unable to fix this properly.

**Comment by bobum** [comment]
Outstanding Wes - thank you for the quick response!  We're enjoying the mod!
